"use client";

import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { coupons, type Coupon } from "../../lib/coupons";
import LiveOffers from "./LiveOffers";

const categories = ["All Deals", "Dining", "Shopping", "Beauty", "Services", "Online", "Other"];

export default function CouponsPage() {
  const [activeCategory, setActiveCategory] = useState("All Deals"); const [query,setQuery]=useState(""); const [liveOffers,setLiveOffers]=useState<Coupon[]>([]); const [sort,setSort]=useState("featured");
  const onLiveOffers=useCallback((offers:Coupon[])=>setLiveOffers(offers),[]); const allCoupons=useMemo(()=>[...liveOffers,...coupons],[liveOffers]);
  const filteredCoupons=useMemo(()=>{const q=query.trim().toLowerCase(); const filtered=allCoupons.filter(c=>(activeCategory==="All Deals"||c.category===activeCategory)&&(!q||`${c.title} ${c.business} ${c.category} ${c.location} ${c.description}`.toLowerCase().includes(q))); return [...filtered].sort((a,b)=>sort==="discount"?b.discount.localeCompare(a.discount):sort==="business"?a.business.localeCompare(b.business):(Number(b.featured)-Number(a.featured)));},[activeCategory,query,allCoupons,sort]);
  return <main className="queen-page"><LiveOffers onLoad={onLiveOffers}/><header className="site-header"><Link href="/" className="brand-wrap" aria-label="Coupon Queen home"><div className="brand-crown">♕</div><div><div className="brand-name">COUPON QUEEN</div><div className="brand-tagline">The Crown Jewel of Savings</div></div></Link><nav aria-label="Main navigation"><Link href="/coupons" aria-current="page">Coupons</Link><Link href="/businesses">Businesses</Link></nav><div className="header-sparkle">✦</div></header>
    <section className="benefits-section"><div className="section-heading"><div className="section-kicker">♛ THE DEAL VAULT ♛</div><h1>Live Deals. Real Savings.</h1><p>Fresh offers from participating businesses, organized so shoppers can find a deal and redeem it in minutes.</p></div>
      <div className="marketplace-strip"><span>● LIVE MARKETPLACE</span><span>✓ Merchant-managed offers</span><span>✓ Unique redemption codes</span><span>✓ One-time verification</span></div>
      <div className="coupon-toolbar"><label className="coupon-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search deals, businesses, categories..." aria-label="Search coupons" /></label><div className="coupon-filters" role="tablist">{categories.map(c=><button key={c} type="button" role="tab" aria-selected={activeCategory===c} className={`filter-pill ${activeCategory===c?"active":""}`} onClick={()=>setActiveCategory(c)}>{c}</button>)}</div></div>
      <div className="coupon-results-bar"><span><strong>{filteredCoupons.length}</strong> {filteredCoupons.length===1?"deal":"deals"} available</span><label className="sort-control">Sort <select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort deals"><option value="featured">Featured</option><option value="business">Business name</option><option value="discount">Discount</option></select></label>{(query||activeCategory!=="All Deals")&&<button type="button" className="clear-filters" onClick={()=>{setQuery("");setActiveCategory("All Deals")}}>Clear filters ×</button>}</div>
      <div className="benefit-grid">{filteredCoupons.map(c=><article key={c.id} className={`benefit-card ${c.featured?"featured-card":""}`}><div className="card-icon gold-icon">🎟️</div><div className="card-number">{c.discount}</div><div className="coupon-category">{c.category}</div><h3>{c.title}</h3><p><strong>{c.business}</strong><br/>{c.description}</p><div className="coupon-meta"><span>♢ {c.category}</span><span>📍 {c.location}</span></div><div className="coupon-expiry">♛ {c.expires}</div><Link href={`/coupons/${c.id}`} className="card-link">Get Deal <span>→</span></Link></article>)}</div>
      {filteredCoupons.length===0&&<div className="empty-coupon-state"><div className="card-icon gold-icon">👑</div><h2>No matching deals</h2><p>Try a different business, category, or search phrase.</p><button type="button" className="queen-button primary-button" onClick={()=>{setQuery("");setActiveCategory("All Deals")}}>Show All Deals</button></div>}
    </section><section className="royal-banner"><div className="banner-diamond">◆</div><div><div className="banner-kicker">FOR LOCAL BUSINESSES</div><h2>Have a deal worth crowning?</h2></div><Link href="/businesses/login?mode=signup" className="queen-button secondary-button">Join the Kingdom <span className="button-arrow">→</span></Link></section><footer className="site-footer"><Link href="/" className="footer-brand"><span>♕</span>COUPON QUEEN</Link><div className="footer-tagline">The Crown Jewel of Savings</div><div className="footer-sparkles">✦ ✧ ✦</div></footer><style jsx>{`.marketplace-strip{display:flex;flex-wrap:wrap;gap:10px;justify-content:center;margin:0 auto 28px}.marketplace-strip span{padding:8px 12px;border:1px solid var(--queen-border);border-radius:999px;background:white;color:var(--queen-muted);font-size:12px;font-weight:800}.marketplace-strip span:first-child{color:var(--queen-turquoise-dark);border-color:rgba(32,199,201,.35)}.sort-control{display:flex;align-items:center;gap:8px;color:var(--queen-muted);font-size:12px;font-weight:800}.sort-control select{padding:8px 10px;border:1px solid var(--queen-border);border-radius:10px;background:white;color:var(--queen-espresso);font:inherit}.card-link{display:inline-flex;align-items:center;gap:8px;margin-top:16px;font-weight:900;color:var(--queen-turquoise-dark);text-decoration:none}.card-link:hover{text-decoration:underline}@media(max-width:620px){.marketplace-strip{justify-content:flex-start}.coupon-results-bar{gap:12px;align-items:flex-start;flex-wrap:wrap}}`}</style></main>;
}
