"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export default function RedeemPage(){
 const params=useParams<{code:string}>(); const code=params.code; const [merchant,setMerchant]=useState<{id:string;business_name:string}|null>(null); const [signedIn,setSignedIn]=useState(false); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const token=localStorage.getItem("cq_access_token");if(!token||!SUPABASE_URL||!SUPABASE_KEY)return;setSignedIn(true);const h={apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`};const memberRes=await fetch(`${SUPABASE_URL}/rest/v1/merchant_members?user_id=eq.${encodeURIComponent((await (await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:h})).json()).id)}&select=merchant_id&limit=1`,{headers:h,cache:"no-store"});if(!memberRes.ok)return;const members=await memberRes.json();if(!members[0]?.merchant_id)return;const merchantRes=await fetch(`${SUPABASE_URL}/rest/v1/merchants?id=eq.${members[0].merchant_id}&select=id,business_name&limit=1`,{headers:h,cache:"no-store"});if(merchantRes.ok){const rows=await merchantRes.json();if(rows[0])setMerchant(rows[0])}}catch{}})()},[]);
 async function verify(){if(!merchant)return;setBusy(true);setError("");try{const token=localStorage.getItem("cq_access_token");if(!token||!SUPABASE_URL||!SUPABASE_KEY)throw new Error("Merchant sign-in is required.");const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/redeem_coupon`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({p_redemption_token:code,p_merchant_id:merchant.id})});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.message||body?.hint||"This claim could not be verified.");setDone(true)}catch(e){setError(e instanceof Error?e.message:"Verification failed.")}finally{setBusy(false)}}
 return <main className="queen-page"><header className="site-header"><Link href="/" className="brand-wrap"><div className="brand-crown">♕</div><div><div className="brand-name">COUPON QUEEN</div><div className="brand-tagline">The Crown Jewel of Savings</div></div></Link><nav><Link href="/coupons">Deal Vault</Link><Link href="/businesses">Businesses</Link></nav></header><section className="redeem-shell"><div className="redeem-card">{done?<><div className="verified">✓</div><div className="section-kicker">CLAIM VERIFIED</div><h1>Royal Savings Redeemed</h1><p>This Coupon Queen claim has been successfully recorded for {merchant?.business_name}.</p><Link href="/businesses/dashboard" className="queen-button primary-button">Back to Merchant Kingdom</Link></>:<><div className="section-kicker">♕ COUPON QUEEN REDEMPTION</div><h1>Verify This Claim</h1><p className="redeem-intro">This QR code represents a customer claim. Only an authenticated merchant team member can complete the redemption.</p><div className="claim-token">{code}</div>{merchant?<><div className="merchant-badge">♛ {merchant.business_name}</div><button className="queen-button primary-button" onClick={verify} disabled={busy}>{busy?"Verifying…":"Verify & Redeem Claim →"}</button></>:signedIn?<p className="redeem-error">Your account is not connected to a merchant team.</p>:<><Link href="/businesses/login" className="queen-button primary-button">Merchant Sign In →</Link><p className="redeem-note">Customer? Show this screen to the merchant. They can scan or enter the claim from their merchant account.</p></>}{error&&<p className="redeem-error">{error}</p>}</>}</div></section><style jsx>{`.redeem-shell{max-width:620px;margin:0 auto;padding:65px 22px 100px}.redeem-card{padding:45px 35px;text-align:center;border:1px solid var(--queen-border);border-radius:30px;background:white;box-shadow:0 25px 70px rgba(53,32,24,.12)}.redeem-card h1{margin:12px 0;color:var(--queen-espresso);font-size:clamp(35px,7vw,55px);line-height:1}.redeem-intro,.redeem-card>p{color:var(--queen-muted);line-height:1.7}.claim-token{margin:25px 0;padding:18px 14px;border:1px dashed var(--queen-gold);border-radius:14px;background:var(--queen-cream);color:var(--queen-espresso);font-size:12px;font-weight:900;word-break:break-all}.merchant-badge{margin:18px 0;padding:11px;border-radius:12px;background:rgba(32,199,201,.08);color:var(--queen-turquoise-dark);font-weight:900}.verified{display:grid;place-items:center;width:72px;height:72px;margin:0 auto 18px;border-radius:50%;background:rgba(32,199,201,.12);color:var(--queen-turquoise-dark);font-size:38px;font-weight:950}.redeem-error{margin-top:16px;color:#9b2c2c!important;font-weight:850}.redeem-note{font-size:11px!important}.redeem-card .queen-button{margin-top:12px}`}</style></main>;
}
